DROP TABLE IF EXISTS `user_dtl`;
DROP TABLE IF EXISTS `user_xml`;

CREATE TABLE user_dtl (
   id INT AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR(100) NOT NULL,
   birthday DATE NOT NULL,
   createts TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
   CONSTRAINT uk_name UNIQUE (name)
);

CREATE TABLE user_xml (
   id INT AUTO_INCREMENT PRIMARY KEY,
   xml BLOB NOT NULL
);